### ISSUE TITLE
error no clientIds not defined

### ISSUE THREAD

**Issue by charlicruz** [stfbk/mqttsa#1]
Hi, 
when I run the code, some warnings come up (attached).Do these warnings need to be taken into account? I also would like to test DOING BRUTEFORCE but I don't know how to setup -w WORDLIST_PATH. How do I need to  specify for the path to the wordlist?
Thanks

File "/Users/xxxx/opt/anaconda3/lib/python3.7/site-packages/pyshark/capture/capture.py", line 293, in packets_from_tshark
    await self.close_async()
  File "/Users/xxxx/opt/anaconda3/lib/python3.7/site-packages/pyshark/capture/capture.py", line 441, in close_async
    await self._cleanup_subprocess(process)
  File "/Users/xxxxx/opt/anaconda3/lib/python3.7/site-packages/pyshark/capture/capture.py", line 434, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

**Comment by umorelli** [comment]
Hi charlicruz, sorry for the extreme late reply. I believe the warnings/errors were related to the installed _pyshark_ version.
Everyting seems to work using the official Python 3.7 Docker container. To test, run:
`docker run --rm -it python:3.7-buster bash`
then, from the running container:
```
apt update && apt install -y git mosquitto mosquitto-clients tshark
git clone https://github.com/stfbk/mqttsa.git
cd mqttsa && make
python3 mqttsa.py -t 5 --ni test.mosquitto.org
python3 mqttsa.py -t 10 -fc 10 -sc 10 -mq 10 -mp 10 --md 127.0.0.1
```
To perform the _bruteforce_ attack, you would have run the tool by specifying a username and the full file path of a password list (a file with a password on each line). For instance `python3 mqttsa.py -u "User1" -w "C:\Users\<user>\mqttsa\src\words.txt" <IP>`.
