### ISSUE TITLE
Brute force

### ISSUE THREAD

**Issue by aycakahya** [stfbk/mqttsa#3]
(base) C:\spark-3.1.1-bin-hadoop3.2\mqttsa-master\mqttsa-master>python mqttsa.py -p XXXX -u UsernameXX -w /src/words.txt broker.XXXX.com

[!] "t" parameter < 1 or not specified, setting listening time to 60s
[!] "dos_fooding_conn" parameter < 1 or not specified, no flooding-based DoS attack
[!] "dos_slow_conn" parameter < 1 or not specified, no slow DoS attack
[!] "max_queue" parameter < 0 or null, no message queue test
[!] "max_payload" parameter < 0 or null, no payload size test
[!] Error: verify the wordlist path /src/words.txt

(base) C:\spark-3.1.1-bin-hadoop3.2\mqttsa-master\mqttsa-master>

Hello,
Where am I making a mistake? 
I want to start a brute force attack. Why didn't it happen?

**Comment by umorelli** [comment]
Hi, sorry for the extremely late reply. To perform the brute-force attack, you would have run the tool by specifying a username and the full file path of a password list (a file with a password on each line). For instance using `python3 mqttsa.py -u "User1" -w "C:\Users\<user>\mqttsa\src\words.txt" <IP>`. Bear in mind, however, that no standard/default set of passwords exists in the IoT domain (words.txt was built upon merging defaults from different environments).
